version: '3'

services:
  app:
    container_name: service1
    restart: always
    build: .
    ports:
      - '3005:3005'
    links:
      - mongo
      - rabbitmq
    volumes:
      - .:/lostme-backend/src
  
  mongo:
    container_name: dbmongo
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - mongodata:/data/db
  
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:management-alpine
    ports: 
      - '15672:15672'
      - '5672:5672'

volumes:
  mongodata: